// SPDX-License-Identifier: Apache-2.0
// EN: image_decode_probe_corpus_sanity (`DEC-PROBE-CORPUS`, W27, TODO.md) -- regression test
//     for the `DEC-NOTHROW` (A-1) and `DEC-FORMAT-SURFACE` (A-2) findings that exercises
//     `glintfx::decode_image_file()`/`decode_png_file()` against the CONSUMER'S OWN corpus
//     bytes, generated by the adopted, verbatim `tests/tools/gen_corpus.py` (see that file's
//     own top comment for provenance: gusworld's `assets/probe-decode/gen_corpus.py`, bus
//     commit `882cae0766fb3cdf5c43410b86148aa1f87557cf`, `md5sum`-verified `cp`, byte-
//     identical below its provenance header) rather than a stand-in re-derived from a prose
//     description of the bugs -- the whole argument this item exists to generalise: "if the
//     test of the fix uses the SAME input that caught the bug, it proves the fix catches THIS
//     case; a test written from the description risks exercising a neighbour and passing for
//     the wrong reason" (`DEC-PROBE-CORPUS`, `TODO.md`).
//
//     WHERE THE CORPUS COMES FROM, AND WHY THIS FILE NEVER WRITES ONE: `tests/CMakeLists.txt`
//     runs `tests/tools/gen_corpus.py` via a `add_custom_command()` exactly ONCE, at BUILD
//     time (never at ctest time, never per-process), into a build-tree directory this
//     translation unit receives as the compiled-in `GLINTFX_PROBE_CORPUS_DIR` string (a
//     `target_compile_definitions()` value, not a `WORKING_DIRECTORY`-relative guess -- this
//     test runs correctly regardless of what CWD ctest happens to invoke it from). The
//     generated bytes are NEVER committed to this repository (only the generator is -- see
//     `gen_corpus.py`'s own provenance header) and this file itself performs ZERO writes: it
//     only opens the two fixtures the build already produced, read-only. This SIDESTEPS,
//     rather than mitigates, the W27 `.ppm`-fixed-name-in-CWD race this wave's own audit
//     found across nine other tests (three literal `"out.ppm"` collisions plus two each of
//     `"sanity_out.ppm"`/`"tex_out.ppm"`) -- there is no per-process write to race over in the
//     first place, which is a strictly stronger guarantee than giving each process its own
//     PID-suffixed path would be.
//
//     DETERMINISM, independently verified before this file was written (not merely asserted):
//     `tests/tools/gen_corpus.py <dir1>` and `... <dir2>`, run back to back, produced 31/31
//     byte-identical regular files (`md5sum`), including BOTH fixtures this file reads --
//     `png_pal_12000.png` (`c73f1af457c6d5b2fc25cac4f10db373`) and `fake_tga_garbage.png`
//     (`65c2c58c843fd97ff160031a3140436f`, whose own `sha256sum`,
//     `1dc442ea6d179c0e9f2d13f6ce1a4d68d9ff8cb7afacc514b8851a7cb93a5982`, matches the literal
//     byte array `image_png_only_sanity.cpp` already hand-embeds under the SAME provenance
//     claim -- an independent cross-check that the generator's current output is still the
//     bytes this codebase already trusted, not a silent drift).
//
//     GROUP 1 (`DEC-FORMAT-SURFACE`, A-2) -- `fake_tga_garbage.png`: an 18-byte plausible TGA
//     header (image_type=2, 4096x4096, 32bpp) followed by 64 bytes of fixed-seed noise (82
//     bytes total). 1a documents the coador this slice does not change: the GENERAL dispatch
//     (`decode_image_memory()`) still accepts it, "successfully" decoding a 4096x4096,
//     all-zero-alpha image. 1b is THE regression pin: `decode_png_file()` rejects the exact
//     same, LIVE-GENERATED bytes (`ok == false`) -- mirrors `image_png_only_sanity.cpp`'s own
//     Group 1, but sourced from the adopted generator instead of a hand-transcribed literal.
//
//     GROUP 2 (`DEC-NOTHROW`, A-1) -- `png_pal_12000.png`: the consumer's own 12000x12000
//     PALETTED PNG (144 Mpx, 576 MiB decoded RGBA8, ~212 KiB on disk because the four repeated
//     row patterns compress almost entirely away -- see that fixture's own generation comment
//     in `gen_corpus.py` for why paletted specifically forces the intermediate stb buffer
//     BELOW this library's own added `assign()` copy, the exact shape that makes `DEC-NOTHROW`
//     reproducible at all). Reuses the SAME two-stage fork()+`setrlimit(RLIMIT_AS)`
//     calibrate-then-squeeze oracle `image_decode_hardening_sanity.cpp`'s own Group B already
//     proved (STAGE 1/2 measures the REAL `VmPeak` delta an unconstrained decode of THIS
//     exact file needs; STAGE 2/2 squeezes a second child to 9/10 of that measured delta --
//     NOT the 3/4 that file's own Group B uses for its much smaller fixture, see STAGE 2/2's
//     own comment below for the measured, bisected reason the fraction does not carry over --
//     short of what STAGE 1/2 proved was needed, so an allocation inside the call must
//     genuinely fail) -- reimplemented HERE, independently, rather than shared via a common header,
//     because this file and `image_decode_hardening_sanity.cpp` are owned by different W27
//     slices editing disjoint files in the same wave (house rule against cross-file coupling
//     between parallel agents' work). Measured, on this fixture, BEFORE this file was wired
//     into the build (a throwaway probe outside the repo, linked against the already-built
//     `libglintfx.a`): calibration delta ~1099 MiB, total wall time ~1.05 s, peak RSS ~1.1
//     GiB -- comfortably inside the self-hosted heavy runner's 8 GiB cap (`AGENTS.md`) and
//     fast enough to run on every `ctest` invocation, not just on demand.
//
//     `probe_mem.cpp` (the bus's OTHER file, same commit, `assets/probe-decode/`) was NOT
//     adopted byte-for-byte the way `gen_corpus.py` was -- see `gen_corpus.py`'s own
//     provenance header for why. Its ~50-line METHOD is cited here instead: read a process's
//     own `VmHWM`/`VmPeak` from `/proc/self/status`, run exactly ONE decode call inside a
//     `try` that wraps only it, and report the `typeid` of any exception that escapes. STAGE
//     1/2 below follows that same shape (measure peak virtual-memory growth around a single
//     decode call) but reads `VmPeak` rather than `VmHWM` (matching, not diverging from, what
//     `image_decode_hardening_sanity.cpp`'s own Group B already established and proved works
//     for this exact oracle -- see that file's own history in its top comment for why `VmHWM`
//     alone under-measured a transient peak the two-stage design needs to reproduce). The
//     `typeid`-on-catch half of `probe_mem.cpp`'s technique is unnecessary here: this oracle's
//     observable is the PARENT's `waitpid()`-and-`WIFSIGNALED()` check on the child (an
//     uncaught `std::bad_alloc` -> `std::terminate()` -> `abort()` -> `SIGABRT`, the exact
//     `DEC-NOTHROW` regression this test exists to catch), not a same-process `catch` clause.
//
//     Runs UNCONDITIONALLY, in BOTH build configurations -- no RmlUi/GL/window dependency
//     whatsoever, same "nothing display-related to isolate here" reasoning as
//     image_decode_sanity.cpp/image_sanity.cpp/image_decode_hardening_sanity.cpp above. Linux-
//     only (`/proc/self/status`, `fork()`, `setrlimit()`), matching this whole library's
//     "Linux x86-64" platform scope (`CLAUDE.md`) -- no `#ifdef` needed. Registered ONLY when
//     `tests/CMakeLists.txt`'s own configure-time Python3+Pillow capability check succeeds
//     (`gen_corpus.py` imports `PIL.Image` unconditionally at module scope, for fixtures this
//     file does not even read -- the two fixtures THIS file needs, `png_pal_12000.png` and
//     `fake_tga_garbage.png`, are built by the script's own hand-rolled `raw_png()`/PNG-chunk
//     helpers with no PIL dependency, but they sit downstream, in file order, of several
//     `PIL.Image.new()` calls the unmodified, adopted script runs first -- so reaching either
//     fixture still requires Pillow to be importable, even though neither fixture's own bytes
//     depend on it); see `tests/CMakeLists.txt`'s own comment on that gate, and its
//     `message(WARNING ...)`, for what happens when the capability check fails (this target is
//     simply not registered -- an honest absence in the configure log, never a silent skip
//     inside a test that claims to have run).
// PT: image_decode_probe_corpus_sanity (`DEC-PROBE-CORPUS`, W27, TODO.md) -- teste de
//     regressão para os achados `DEC-NOTHROW` (A-1) e `DEC-FORMAT-SURFACE` (A-2) que exercita
//     `glintfx::decode_image_file()`/`decode_png_file()` contra os PRÓPRIOS bytes de corpus do
//     consumidor, gerados pelo `tests/tools/gen_corpus.py` adotado, verbatim (ver o próprio
//     comentário de topo daquele arquivo pra proveniência: `assets/probe-decode/gen_corpus.py`
//     do gusworld, commit do bus `882cae0766fb3cdf5c43410b86148aa1f87557cf`, `cp` verificado
//     por `md5sum`, byte-idêntico abaixo do próprio cabeçalho de proveniência) em vez de um
//     substituto re-derivado de uma descrição em prosa dos bugs -- o argumento inteiro que
//     este item existe pra generalizar: "se o teste do conserto usar a MESMA entrada que
//     pegou o bug, ele prova que o conserto pega ESTE caso; um teste escrito da descrição
//     corre o risco de exercitar um vizinho e passar por motivo errado" (`DEC-PROBE-CORPUS`,
//     `TODO.md`).
//
//     DE ONDE O CORPUS VEM, E POR QUE ESTE ARQUIVO NUNCA ESCREVE UM: `tests/CMakeLists.txt`
//     roda `tests/tools/gen_corpus.py` via um `add_custom_command()` exatamente UMA vez, em
//     BUILD time (nunca em test time, nunca por processo), num diretório da árvore de build
//     que esta unidade de tradução recebe como a string `GLINTFX_PROBE_CORPUS_DIR` embutida em
//     compilação (um valor de `target_compile_definitions()`, não um palpite relativo a
//     `WORKING_DIRECTORY` -- este teste roda certo independente de qual CWD o ctest invoca
//     ele). Os bytes gerados NUNCA são commitados neste repositório (só o gerador é -- ver o
//     próprio cabeçalho de proveniência de `gen_corpus.py`) e este arquivo em si faz ZERO
//     escritas: só abre as duas fixtures que o build já produziu, somente-leitura. Isto
//     CONTORNA, em vez de mitigar, a corrida de nome-fixo-de-`.ppm`-no-CWD que a própria
//     auditoria desta onda W27 achou em nove outros testes (três colisões literais de
//     `"out.ppm"` mais duas cada de `"sanity_out.ppm"`/`"tex_out.ppm"`) -- não existe escrita
//     por processo pra correr, em primeiro lugar, o que é uma garantia estritamente mais forte
//     do que dar a cada processo o próprio caminho sufixado por PID seria.
//
//     DETERMINISMO, verificado de forma independente antes deste arquivo ser escrito (não
//     apenas afirmado): `tests/tools/gen_corpus.py <dir1>` e `... <dir2>`, rodados em
//     sequência, produziram 31/31 arquivos regulares byte-idênticos (`md5sum`), incluindo as
//     DUAS fixtures que este arquivo lê -- `png_pal_12000.png`
//     (`c73f1af457c6d5b2fc25cac4f10db373`) e `fake_tga_garbage.png`
//     (`65c2c58c843fd97ff160031a3140436f`, cujo próprio `sha256sum`,
//     `1dc442ea6d179c0e9f2d13f6ce1a4d68d9ff8cb7afacc514b8851a7cb93a5982`, casa com o array de
//     bytes literal que `image_png_only_sanity.cpp` já embute à mão sob a MESMA alegação de
//     proveniência -- uma checagem cruzada independente de que a saída atual do gerador ainda
//     são os bytes que este código-base já confiava, não uma deriva silenciosa).
//
//     GRUPO 1 (`DEC-FORMAT-SURFACE`, A-2) -- `fake_tga_garbage.png`: um header TGA plausível de
//     18 bytes (image_type=2, 4096x4096, 32bpp) seguido de 64 bytes de ruído de semente fixa
//     (82 bytes no total). O 1a documenta o coador que esta fatia não muda: o dispatch GERAL
//     (`decode_image_memory()`) continua aceitando, decodificando "com sucesso" numa imagem
//     4096x4096 alpha-zero-em-tudo. O 1b é A prova da regressão: `decode_png_file()` rejeita
//     os MESMOS bytes, GERADOS AO VIVO (`ok == false`) -- espelha o próprio Grupo 1 de
//     `image_png_only_sanity.cpp`, mas vindo do gerador adotado em vez de um literal
//     transcrito à mão.
//
//     GRUPO 2 (`DEC-NOTHROW`, A-1) -- `png_pal_12000.png`: o próprio PNG PALETIZADO
//     12000x12000 do consumidor (144 Mpx, 576 MiB decodificado em RGBA8, ~212 KiB em disco
//     porque os quatro padrões de linha repetidos comprimem quase por inteiro -- ver o próprio
//     comentário de geração desta fixture em `gen_corpus.py` pro porquê de paletizado
//     especificamente forçar o buffer intermediário do stb ABAIXO da própria cópia `assign()`
//     somada por esta biblioteca, a forma exata que torna o `DEC-NOTHROW` reproduzível de
//     verdade). Reusa o MESMO oráculo de dois estágios fork()+`setrlimit(RLIMIT_AS)`
//     calibrar-depois-apertar que o próprio Grupo B de `image_decode_hardening_sanity.cpp` já
//     provou (o ESTÁGIO 1/2 mede o `VmPeak` REAL que um decode não-restringido DESTE arquivo
//     exato precisa; o ESTÁGIO 2/2 aperta um segundo filho pra 9/10 daquele delta medido --
//     NÃO o 3/4 que o Grupo B daquele arquivo usa pra fixture BEM menor dele, ver o próprio
//     comentário do ESTÁGIO 2/2 mais abaixo pro motivo medido, por bisecção, da fração não se
//     repetir -- abaixo do que o ESTÁGIO 1/2 provou ser necessário, então uma alocação dentro da chamada precisa
//     falhar de verdade) -- reimplementado AQUI, de forma independente, em vez de compartilhado
//     via um header comum, porque este arquivo e `image_decode_hardening_sanity.cpp` são
//     donos de fatias W27 diferentes editando arquivos disjuntos na mesma onda (regra da casa
//     contra acoplamento entre arquivos de agentes paralelos). Medido, nesta fixture, ANTES
//     deste arquivo ser conectado ao build (uma sonda descartável fora do repo, linkada contra
//     o `libglintfx.a` já buildado): delta de calibração ~1099 MiB, tempo total de parede
//     ~1,05 s, RSS de pico ~1,1 GiB -- confortavelmente dentro do teto de 8 GiB do runner
//     pesado self-hosted (`AGENTS.md`) e rápido o bastante pra rodar em toda invocação do
//     `ctest`, não só sob demanda.
//
//     `probe_mem.cpp` (o OUTRO arquivo do bus, mesmo commit, `assets/probe-decode/`) NÃO foi
//     adotado byte-a-byte como o `gen_corpus.py` foi -- ver o próprio cabeçalho de proveniência
//     de `gen_corpus.py` pro porquê. O MÉTODO dele de ~50 linhas é citado aqui em vez disso:
//     ler o próprio `VmHWM`/`VmPeak` de um processo de `/proc/self/status`, rodar exatamente
//     UMA chamada de decode dentro de um `try` que envolve só ela, e reportar o `typeid` de
//     qualquer exceção que escape. O ESTÁGIO 1/2 abaixo segue essa mesma forma (medir o
//     crescimento de pico de memória virtual em volta de UMA chamada de decode) mas lê
//     `VmPeak` em vez de `VmHWM` (casando, não divergindo, do que o próprio Grupo B de
//     `image_decode_hardening_sanity.cpp` já estabeleceu e provou funcionar pra este oráculo
//     exato -- ver o próprio histórico daquele arquivo no comentário de topo dele pro porquê de
//     `VmHWM` sozinho sub-medir um pico transitório que o desenho de dois estágios precisa
//     reproduzir). A metade `typeid`-no-catch da técnica de `probe_mem.cpp` é desnecessária
//     aqui: o observável deste oráculo é a checagem `waitpid()`-e-`WIFSIGNALED()` do PAI sobre
//     o filho (um `std::bad_alloc` não-capturado -> `std::terminate()` -> `abort()` ->
//     `SIGABRT`, a regressão exata de `DEC-NOTHROW` que este teste existe pra pegar), não uma
//     cláusula `catch` no mesmo processo.
//
//     Roda INCONDICIONALMENTE, nas DUAS configurações de build -- nenhuma dependência de
//     RmlUi/GL/janela, mesmo racional "nada relacionado a display pra isolar aqui" de
//     image_decode_sanity.cpp/image_sanity.cpp/image_decode_hardening_sanity.cpp acima. Só
//     Linux (`/proc/self/status`, `fork()`, `setrlimit()`), casando com o próprio escopo de
//     plataforma "Linux x86-64" de toda esta biblioteca (`CLAUDE.md`) -- nenhum `#ifdef`
//     necessário. Registrado SÓ quando a própria checagem de capacidade Python3+Pillow em
//     tempo de configure de `tests/CMakeLists.txt` tem sucesso (`gen_corpus.py` importa
//     `PIL.Image` incondicionalmente no escopo do módulo, pra fixtures que este arquivo nem
//     lê -- as duas fixtures que ESTE arquivo precisa, `png_pal_12000.png` e
//     `fake_tga_garbage.png`, são construídas pelos próprios helpers de PNG-chunk/`raw_png()`
//     feitos à mão do script, sem dependência de PIL, mas ficam depois, na ordem do arquivo,
//     de várias chamadas `PIL.Image.new()` que o script adotado, não-modificado, roda antes --
//     então alcançar qualquer uma das duas fixtures ainda exige que o Pillow seja importável,
//     mesmo que os próprios bytes de nenhuma das duas dependam dele); ver o próprio comentário
//     de `tests/CMakeLists.txt` sobre essa guarda, e o próprio `message(WARNING ...)`, pro que
//     acontece quando a checagem de capacidade falha (este alvo simplesmente não é registrado
//     -- uma ausência honesta no log de configure, nunca um skip silencioso dentro de um teste
//     que alega ter rodado).
// Copyright (c) 2026 Petrus Silva Costa
#include "glintfx/image.hpp"

#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>

#include <sys/resource.h>
#include <sys/wait.h>
#include <unistd.h>

#ifndef GLINTFX_PROBE_CORPUS_DIR
#error "GLINTFX_PROBE_CORPUS_DIR must be supplied by tests/CMakeLists.txt (build-time corpus dir)"
#endif

namespace {

int g_failures = 0;

void check(bool cond, const char* what) {
  if (!cond) {
    std::fprintf(stderr, "FAIL: %s\n", what);
    ++g_failures;
  }
}

std::string corpus_path(const char* fixture_name) {
  return std::string(GLINTFX_PROBE_CORPUS_DIR) + "/" + fixture_name;
}

// EN: Reads an entire file into memory, for the general-dispatch (decode_image_memory())
//     leg of Group 1, which takes bytes rather than a path. Returns an empty vector on any
//     I/O failure -- the caller's own check() reports that as a setup failure, distinct from
//     the decode assertions that follow.
// PT: Lê um arquivo inteiro pra memória, pra perna de dispatch geral (decode_image_memory())
//     do Grupo 1, que recebe bytes em vez de um path. Devolve um vector vazio em qualquer
//     falha de I/O -- o próprio check() do chamador reporta isso como falha de setup,
//     distinta das asserções de decode que seguem.
std::vector<unsigned char> read_whole_file(const std::string& path) {
  std::ifstream f(path, std::ios::binary);
  if (!f)
    return {};
  return std::vector<unsigned char>(std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>());
}

long read_vm_size_bytes() {
  std::ifstream f("/proc/self/status");
  if (!f)
    return -1;
  std::string line;
  while (std::getline(f, line)) {
    if (line.compare(0, 7, "VmSize:") == 0) {
      std::istringstream iss(line.substr(7));
      long kb = -1;
      iss >> kb;
      if (kb < 0)
        return -1;
      return kb * 1024;
    }
  }
  return -1;
}

} // namespace

using namespace glintfx;

int main() {
  // ===========================================================================================
  // EN: Group 1 (DEC-FORMAT-SURFACE, A-2) -- fake_tga_garbage.png, read from the build-time-
  //     generated corpus (see this file's own top comment for why no write happens here).
  // PT: Grupo 1 (DEC-FORMAT-SURFACE, A-2) -- fake_tga_garbage.png, lido do corpus gerado em
  //     build-time (ver o próprio comentário de topo deste arquivo pro porquê de nenhuma
  //     escrita acontecer aqui).
  // ===========================================================================================
  {
    const std::string path = corpus_path("fake_tga_garbage.png");
    const std::vector<unsigned char> bytes = read_whole_file(path);
    check(bytes.size() == 82,
          "Group 1 setup: fake_tga_garbage.png read from the build-time corpus is exactly 82 bytes");

    if (!bytes.empty()) {
      const DecodedImagePixels general = decode_image_memory(bytes.data(), bytes.size());
      check(general.ok,
            "1a: decode_image_memory (general dispatch) STILL accepts the corpus's 82-byte fake "
            "TGA header -- documents the coador this slice does not change on the general entry "
            "point");
      check(general.width == 4096 && general.height == 4096,
            "1a: general dispatch decodes it as 4096x4096 (the consumer's own measured coador shape)");
      check(general.pixels.size() == 4096u * 4096u * 4u,
            "1a: general dispatch allocates the full 67 108 864-byte all-zero-alpha buffer");
    }

    const DecodedImagePixels restricted = decode_png_file(path.c_str());
    check(!restricted.ok,
          "1b: decode_png_file REJECTS the exact fake-TGA-header bytes the build-time corpus "
          "generated (ok == false) -- THE DEC-FORMAT-SURFACE regression this file exists to pin, "
          "using the consumer's OWN generator output, not a hand-transcribed literal");
  }

  // ===========================================================================================
  // EN: Group 2 (DEC-NOTHROW, A-1) -- png_pal_12000.png, the consumer's own 12000x12000
  //     paletted fixture, read directly by path (no scratch copy needed -- it already exists
  //     on disk, produced once at build time). See this file's own top comment for the full
  //     two-stage calibrate-then-squeeze derivation and the measured cost (~1099 MiB
  //     calibration delta, ~1.05 s wall time, ~1.1 GiB peak RSS).
  // PT: Grupo 2 (DEC-NOTHROW, A-1) -- png_pal_12000.png, a própria fixture paletizada
  //     12000x12000 do consumidor, lida diretamente pelo path (nenhuma cópia de scratch
  //     necessária -- já existe em disco, produzida uma vez em build time). Ver o próprio
  //     comentário de topo deste arquivo pra derivação completa de dois estágios
  //     calibrar-depois-apertar e o custo medido (~1099 MiB de delta de calibração, ~1,05 s de
  //     tempo de parede, ~1,1 GiB de RSS de pico).
  // ===========================================================================================
  {
    const std::string path = corpus_path("png_pal_12000.png");

    // -----------------------------------------------------------------------------------------
    // EN: STAGE 1/2 -- CALIBRATE. Unconstrained child decodes the corpus file to completion
    //     (must succeed) and reports back, via a pipe, VmPeak - baseline: the REAL, measured
    //     virtual-address-space growth THIS exact call needed. See image_decode_hardening_
    //     sanity.cpp's own Group B top comment for why this measure-then-squeeze design
    //     replaced an earlier hand-derived fixed multiplier that undershot the real peak.
    // PT: ESTÁGIO 1/2 -- CALIBRAR. Filho não-restringido decodifica o arquivo do corpus até o
    //     fim (precisa ter sucesso) e reporta de volta, via um pipe, VmPeak - baseline: o
    //     crescimento REAL, medido, de espaço de endereço virtual que ESTA chamada exata
    //     precisou. Ver o próprio comentário de topo do Grupo B de image_decode_hardening_
    //     sanity.cpp pro porquê deste desenho medir-depois-apertar substituir um multiplicador
    //     fixo derivado à mão anterior que ficava abaixo do pico real.
    // -----------------------------------------------------------------------------------------
    int cal_pipe[2] = {-1, -1};
    long cal_delta_bytes = -1;
    bool cal_ok = false;
    if (pipe(cal_pipe) == 0) {
      const pid_t cal_pid = fork();
      check(cal_pid >= 0, "Group 2 calibration: fork() succeeded");
      if (cal_pid == 0) {
        close(cal_pipe[0]);
        const long b = read_vm_size_bytes();
        const DecodedImagePixels decoded = decode_image_file(path.c_str()); // unconstrained -- must succeed.
        long peak_kb = -1;
        std::ifstream f2("/proc/self/status");
        std::string line2;
        while (std::getline(f2, line2)) {
          if (line2.compare(0, 7, "VmPeak:") == 0) {
            std::istringstream iss(line2.substr(7));
            iss >> peak_kb;
            break;
          }
        }
        long delta = (b >= 0 && peak_kb >= 0 && decoded.ok) ? (peak_kb * 1024 - b) : -1;
        const ssize_t written = write(cal_pipe[1], &delta, sizeof(delta));
        (void)written;
        close(cal_pipe[1]);
        _exit(0);
      }
      close(cal_pipe[1]);
      long delta = -1;
      const ssize_t got = read(cal_pipe[0], &delta, sizeof(delta));
      close(cal_pipe[0]);
      int cal_status = 0;
      waitpid(cal_pid, &cal_status, 0);
      if (got == static_cast<ssize_t>(sizeof(delta)) && delta > 0) {
        cal_delta_bytes = delta;
        cal_ok = true;
      }
    }
    check(cal_ok,
          "Group 2 calibration: measured a real, positive peak-usage delta for an unconstrained "
          "decode_image_file(png_pal_12000.png) call");

    if (!cal_ok) {
      std::fprintf(stderr,
                   "Group 2: SKIPPED -- calibration failed (pipe/fork/proc read issue?) -- "
                   "inconclusive, not a failure\n");
    } else {
      const pid_t pid = fork();
      check(pid >= 0, "Group 2: fork() succeeded");

      if (pid == 0) {
        // -------------------------------------------------------------------------------------
        // EN: STAGE 2/2 -- SQUEEZE. baseline + cal_delta_bytes - margin, margin = 1/10 of the
        //     CALIBRATED delta -- NOT the 1/4 image_decode_hardening_sanity.cpp's own Group B
        //     uses for ITS (much smaller, 2560x2048/20 MiB) hand-rolled fixture. Measured, on
        //     THIS 12000x12000/~1099 MiB fixture, BEFORE this margin was picked (a throwaway
        //     bisection probe, DEC-NOTHROW's own try/catch removed in an isolated
        //     `tools/mutation_sandbox.sh` sandbox, never the tracked file): margin fractions
        //     0.05-0.20 reliably land the forced failure INSIDE the C++ `assign()` this
        //     library's own `decode_straight_rgba()` performs (throws `std::bad_alloc` --
        //     exactly what DEC-NOTHROW's `try`/`catch` exists to catch); 0.25 and above
        //     reliably land it INSIDE `stb_image`'s own plain `malloc()` instead (returns
        //     `NULL`, `decode_straight_rgba()` reports `ok == false` with NO exception at all --
        //     an ALREADY-safe path, unaffected by whether DEC-NOTHROW's guard exists). 0.25 is
        //     exactly the fraction that DOES generalise from the smaller fixture; it does NOT
        //     here -- confirmed both ways: with the guard present, 0.10/0.18/0.22 all exited
        //     cleanly with `ok == false` (3 repeats each, zero variance); with the guard
        //     removed, the SAME three fractions all `SIGABRT`ed (3 repeats each, zero
        //     variance). 0.10 is the fraction actually wired in below -- comfortably inside the
        //     confirmed-crashing range, with headroom on BOTH sides of the measured 0.20-0.25
        //     transition (unlike image_decode_hardening_sanity.cpp's own Group B, whose
        //     smaller-margin attempt, 1/16, occasionally let the constrained run "unexpectedly
        //     fit" -- the OPPOSITE failure mode from squeezing too tight -- this fixture's own
        //     bisection showed no such variance even at 0.05, but 0.10 is used rather than 0.05
        //     for the same margin-of-safety reasoning, not because 0.05 itself was observed to
        //     be unstable). The absolute-byte overhead a squeeze margin has to clear (malloc
        //     arena bookkeeping, page rounding, ASLR guard regions) is roughly CONSTANT
        //     regardless of decode size, so it is a much SMALLER fraction of a ~1099 MiB delta
        //     than of a ~20 MiB one -- which is why the two files' own margins differ by a
        //     factor of 2.5x rather than being copy-pasted, and why this file reimplements the
        //     oracle independently instead of sharing a constant with that one (see this file's
        //     own top comment for the disjoint-files-in-the-same-wave reasoning too).
        // PT: ESTÁGIO 2/2 -- APERTAR. baseline + cal_delta_bytes - margem, margem = 1/10 do
        //     delta CALIBRADO -- NÃO o 1/4 que o próprio Grupo B de image_decode_hardening_
        //     sanity.cpp usa pra fixture DELE (bem menor, 2560x2048/20 MiB, feita à mão).
        //     Medido, nesta fixture 12000x12000/~1099 MiB, ANTES desta margem ser escolhida
        //     (uma sonda de bisecção descartável, com o try/catch do DEC-NOTHROW removido num
        //     sandbox isolado do `tools/mutation_sandbox.sh`, nunca no arquivo rastreado):
        //     frações de margem 0.05-0.20 pousam a falha forçada de forma confiável DENTRO do
        //     `assign()` C++ que o próprio `decode_straight_rgba()` desta biblioteca faz (lança
        //     `std::bad_alloc` -- exatamente o que o `try`/`catch` do DEC-NOTHROW existe pra
        //     pegar); 0.25 pra cima pousa de forma confiável DENTRO do `malloc()` puro do
        //     próprio `stb_image` (devolve `NULL`, `decode_straight_rgba()` reporta
        //     `ok == false` SEM exceção nenhuma -- um caminho JÁ seguro, não afetado por a
        //     guarda do DEC-NOTHROW existir ou não). 0.25 é exatamente a fração que GENERALIZA
        //     da fixture menor; AQUI não generaliza -- confirmado dos dois lados: com a guarda
        //     presente, 0.10/0.18/0.22 saíram todas limpas com `ok == false` (3 repetições
        //     cada, variância zero); com a guarda removida, as MESMAS três frações deram
        //     `SIGABRT` todas (3 repetições cada, variância zero). 0.10 é a fração de fato
        //     conectada abaixo -- confortavelmente dentro da faixa confirmada-que-crasha, com
        //     folga dos DOIS lados da transição medida 0.20-0.25 (diferente do próprio Grupo B
        //     de image_decode_hardening_sanity.cpp, cuja tentativa de margem menor, 1/16,
        //     ocasionalmente deixava a execução restringida "caber inesperadamente" -- o modo
        //     de falha OPOSTO de apertar demais -- a bisecção desta fixture não mostrou
        //     variância nenhuma nem em 0.05, mas 0.10 é usado em vez de 0.05 pelo mesmo
        //     racional de margem-de-segurança, não porque 0.05 em si tenha sido observado
        //     instável). O overhead em bytes absolutos que uma margem de aperto precisa
        //     superar (contabilidade de arena do malloc, arredondamento de página, regiões de
        //     guarda ASLR) é aproximadamente CONSTANTE independente do tamanho do decode,
        //     então é uma fração bem MENOR de um delta de ~1099 MiB do que de um de ~20 MiB --
        //     por isso as margens dos dois arquivos diferem por um fator de 2,5x em vez de
        //     serem copiadas-e-coladas, e por isso este arquivo reimplementa o oráculo de
        //     forma independente em vez de compartilhar uma constante com aquele (ver o
        //     próprio comentário de topo deste arquivo pro racional de arquivos-disjuntos-na-
        //     mesma-onda também).
        // -------------------------------------------------------------------------------------
        const long baseline = read_vm_size_bytes();
        if (baseline < 0)
          _exit(2); // EN: cannot measure -- inconclusive. PT: não dá pra medir -- inconclusivo.

        const long margin = cal_delta_bytes / 10;
        const rlim_t limit = static_cast<rlim_t>(baseline) + static_cast<rlim_t>(cal_delta_bytes - margin);
        struct rlimit rl;
        rl.rlim_cur = limit;
        rl.rlim_max = limit;
        if (setrlimit(RLIMIT_AS, &rl) != 0)
          _exit(3); // EN: could not clamp -- inconclusive. PT: não deu pra apertar -- inconclusivo.

        // EN: THE call under test -- decode_image_file() end-to-end, on the consumer's OWN
        //     bytes. If DEC-NOTHROW regresses, std::bad_alloc propagates out of main()
        //     uncaught -> std::terminate() -> abort() -> SIGABRT, caught by the parent's
        //     WIFSIGNALED() check below.
        // PT: A chamada sob teste -- decode_image_file() ponta-a-ponta, sobre os PRÓPRIOS
        //     bytes do consumidor. Se DEC-NOTHROW regredir, std::bad_alloc se propaga pra fora
        //     do main() não-capturada -> std::terminate() -> abort() -> SIGABRT, pego pela
        //     checagem WIFSIGNALED() do pai abaixo.
        const DecodedImagePixels decoded = decode_image_file(path.c_str());
        _exit(decoded.ok ? 0 : 1); // 0 = unexpectedly fit; 1 = ok==false as expected under the squeeze.
      }

      int status = 0;
      const pid_t waited = waitpid(pid, &status, 0);
      check(waited == pid, "Group 2: waitpid() reaped the forked child");

      const bool signalled = WIFSIGNALED(status);
      char sig_msg[192];
      std::snprintf(sig_msg, sizeof(sig_msg),
                    "Group 2 (DEC-NOTHROW): child decoding png_pal_12000.png was NOT killed by a "
                    "signal (uncaught std::bad_alloc would SIGABRT) -- WIFSIGNALED=%d, signal=%d",
                    signalled ? 1 : 0, signalled ? WTERMSIG(status) : 0);
      check(!signalled, sig_msg);

      if (!signalled && WIFEXITED(status)) {
        const int code = WEXITSTATUS(status);
        if (code == 2) {
          std::fprintf(stderr,
                       "Group 2: SKIPPED oracle body -- child could not read /proc/self/status "
                       "VmSize (non-Linux or unreadable /proc?) -- inconclusive, not a failure\n");
        } else if (code == 3) {
          std::fprintf(stderr,
                       "Group 2: SKIPPED oracle body -- child's setrlimit(RLIMIT_AS) failed "
                       "(sandboxed/restricted environment?) -- inconclusive, not a failure\n");
        } else {
          check(code == 1,
                "Group 2: decode_image_file(png_pal_12000.png) reported ok == false under the "
                "forced squeeze (exit 1 expected; 0 means the allocation unexpectedly fit -- "
                "widen the budget)");
        }
      }
    }
  }

  if (g_failures > 0) {
    std::fprintf(stderr, "image_decode_probe_corpus_sanity: %d assertion(s) FAILED\n", g_failures);
    return 1;
  }
  std::puts("image_decode_probe_corpus_sanity: PASS");
  return 0;
}
