// SPDX-License-Identifier: AGPL-3.0-or-later
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <format>
#include <fstream>
#include <optional>
#include <print>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

#include <glintfx/core/color.hpp>

#include "gfss/color_parse.hpp"
#include "gfss/named_colors.hpp"

#include "harness/check.hpp"
#include "harness/test_registry.hpp"

// gfss_named_colors_doc_oracle_test.cpp - GFSS-COLOR-ORACLE (TODO.md,
// GODS_LAWS.md L-17/L-20/L-27/L-29/L-36/L-40): the INDEPENDENT witness
// that named_colors.cpp's own 149-row k_table matches the real CSS
// Color Module Level 4 specification - not merely that the code agrees
// with itself. Molded on gfss_declaration_registry_doc_oracle_test.cpp
// (see that file's own header comment for the shared technique); see
// that molde's THE DEFECT paragraph for the general shape this file
// closes a second instance of.
//
// THE DEFECT THIS FILE EXISTS TO CLOSE (achado colateral da revisao de
// GFSS-PROP-REGISTRY, 09/09/2026): gfss_color_parse_test.cpp's own
// gltfx_gfss_parse_color_resolves_every_named_color_keyword enumerates
// all 149 rows and round-trips each through parse_color(), but the
// EXPECTED value it compares against comes from named_color_at(i) -
// the SAME k_table parse_color() is ultimately backed by (through
// lookup_named_color()). A wrong channel baked into that table at
// authoring time (named_colors.cpp was hand-transcribed from the spec,
// per that file's own header comment) would make the code agree with
// itself perfectly, and that loop stays green - see that test's own
// header comment, updated in the same fatia as this file, for the
// "THIS IS NOT THE ORACLE" paragraph making that limitation explicit
// rather than leaving it implicit.
//
// WHY THE FIXTURE IS READ AT TEST TIME, NEVER RETYPED INTO A SECOND
// C++ TABLE HERE (the SAME reasoning gfss_declaration_registry_doc_
// oracle_test.cpp's own header comment already gives for its doc):
// retyping the CSS Color 4 named-color table a second time by hand
// here would carry the exact same transcription-error risk the
// ORIGINAL k_table already carries - not an independent check. Instead,
// tests/fixtures/css_color_4_named_colors.txt is read as a REAL,
// committed file at test run time (GLTFX_GFSS_NAMED_COLORS_FIXTURE_
// SOURCE, tests/CMakeLists.txt) - generated by tests/tools/extract_css_
// named_colors.py from a LOCAL copy of the actual specification source
// text (Overview.bs, pinned to one commit - see that fixture's own
// header for the full provenance), never a value an agent recalled or
// retyped from memory.
//
// WHAT THIS ORACLE DOES NOT ATTEMPT: it checks the 148 OPAQUE named
// colors (CSS Color 4 SS6.1) plus the one special "transparent"
// keyword (SS6.3) - it does NOT check "currentcolor" (SS6.4, a
// different keyword this project's gfss track handles, if at all,
// elsewhere) nor CSS system colors (SS6.2). Those remain out of scope
// for this fixture, which is deliberately narrow to SS6.1+SS6.3.

using namespace glintfx::style::detail;
using glintfx::style::detail::color_parse_result;
using glintfx::style::detail::parse_color;

namespace {

// --- reading the real, committed fixture (gfss_declaration_registry_
// doc_oracle_test.cpp's own read_registry_doc() idiom, GODS_LAWS.md
// L-36: real file, not a copy) -----------------------------------

[[nodiscard]] std::string read_fixture() {
    const std::ifstream in{std::string(GLTFX_GFSS_NAMED_COLORS_FIXTURE_SOURCE)};
    std::ostringstream buffer;
    buffer << in.rdbuf();
    return buffer.str();
}

// --- tiny, hand-rolled fixture reading (GODS_LAWS.md L-07: no
// <regex>, matching this project's own hand-written parser house style
// already set by tokenizer.cpp/selector_parse.cpp and reused by
// gfss_declaration_registry_doc_oracle_test.cpp's own trim()) --------

[[nodiscard]] std::string_view trim(std::string_view s) {
    const std::size_t begin = s.find_first_not_of(" \t\r");
    if (begin == std::string_view::npos) {
        return {};
    }
    const std::size_t end = s.find_last_not_of(" \t\r");
    return s.substr(begin, end - begin + 1);
}

// Splits `line` on runs of ASCII space/tab, dropping empty fields -
// this fixture's own "name r g b" shape (tests/tools/extract_css_
// named_colors.py's own render_fixture_body()), never a single-
// delimiter split that would trip on a stray double space.
[[nodiscard]] std::vector<std::string_view> split_whitespace_fields(std::string_view line) {
    std::vector<std::string_view> fields;
    std::size_t i = 0;
    while (i < line.size()) {
        while (i < line.size() && (line[i] == ' ' || line[i] == '\t')) {
            ++i;
        }
        const std::size_t start = i;
        while (i < line.size() && line[i] != ' ' && line[i] != '\t') {
            ++i;
        }
        if (i > start) {
            fields.push_back(line.substr(start, i - start));
        }
    }
    return fields;
}

[[nodiscard]] std::optional<std::uint8_t> parse_channel(std::string_view text) {
    if (text.empty() || text.size() > 3) {
        return std::nullopt;
    }
    std::uint32_t value = 0;
    for (const char c : text) {
        if (c < '0' || c > '9') {
            return std::nullopt;
        }
        value = value * 10 + static_cast<std::uint32_t>(c - '0');
    }
    if (value > 255) {
        return std::nullopt;
    }
    return static_cast<std::uint8_t>(value);
}

struct fixture_color_row {
    std::string name;
    glintfx::gltfx_rgba8 value{};
};

// One row's own verdict - std::nullopt means the line parsed cleanly;
// anything else names exactly what was wrong with it, printed by the
// caller and folded into the "malformed line" failure the piso de
// varredura (GODS_LAWS.md L-40) requires below.
[[nodiscard]] std::optional<std::string> parse_one_row(std::string_view trimmed,
                                                       fixture_color_row &out) {
    const std::vector<std::string_view> fields = split_whitespace_fields(trimmed);
    if (fields.size() != 4) {
        return std::format("esperava 4 campos (nome r g b), achei {}: \"{}\"", fields.size(),
                           trimmed);
    }
    const std::optional<std::uint8_t> r = parse_channel(fields[1]);
    const std::optional<std::uint8_t> g = parse_channel(fields[2]);
    const std::optional<std::uint8_t> b = parse_channel(fields[3]);
    if (!r || !g || !b) {
        return std::format("canal fora de 0..255 ou nao-numerico em \"{}\"", trimmed);
    }
    out.name = std::string(fields[0]);
    out.value = glintfx::gltfx_rgba8{.red = *r, .green = *g, .blue = *b, .alpha = 255};
    return std::nullopt;
}

// Every non-comment, non-blank line of `text`, in order - a malformed
// line is a HARD failure (GLINTFX_CHECK below), never silently
// skipped, which would shrink the count this file's own piso compares
// against 148 without saying why.
[[nodiscard]] std::vector<fixture_color_row> parse_fixture_rows(std::string_view text) {
    std::vector<fixture_color_row> rows;
    std::size_t pos = 0;
    while (pos <= text.size()) {
        const std::size_t newline = text.find('\n', pos);
        const std::string_view line = text.substr(
            pos, newline == std::string_view::npos ? std::string_view::npos : newline - pos);
        const std::string_view trimmed = trim(line);
        if (!trimmed.empty() && trimmed.front() != '#') {
            fixture_color_row row;
            const std::optional<std::string> error = parse_one_row(trimmed, row);
            if (error) {
                std::println(stderr, "parse_fixture_rows: linha malformada - {}", *error);
                GLINTFX_CHECK(false);
            }
            rows.push_back(std::move(row));
        }
        if (newline == std::string_view::npos) {
            break;
        }
        pos = newline + 1;
    }
    return rows;
}

[[nodiscard]] std::vector<std::string> sorted_names(const std::vector<fixture_color_row> &rows) {
    std::vector<std::string> names;
    names.reserve(rows.size());
    for (const fixture_color_row &row : rows) {
        names.push_back(row.name);
    }
    std::ranges::sort(names);
    return names;
}

[[nodiscard]] bool channels_equal(glintfx::gltfx_rgba8 a, glintfx::gltfx_rgba8 b) {
    return a.red == b.red && a.green == b.green && a.blue == b.blue && a.alpha == b.alpha;
}

} // namespace

// --- the piso de varredura nao-vazia, checked BEFORE any row-by-row
// comparison below trusts the fixture at all (GODS_LAWS.md L-40): a
// broken read (wrong path, empty file) must fail loud here, never read
// as "0 clean rows, nothing to report".

GLINTFX_TEST(fixture_extraction_finds_the_whole_closed_named_color_table_first) {
    const std::string fixture_text = read_fixture();
    GLINTFX_CHECK(!fixture_text.empty());

    const std::vector<fixture_color_row> rows = parse_fixture_rows(fixture_text);

    std::println("fixture_extraction_finds_the_whole_closed_named_color_table_first: {} row(s) "
                 "parsed from {}",
                 rows.size(), GLTFX_GFSS_NAMED_COLORS_FIXTURE_SOURCE);

    GLINTFX_CHECK(rows.size() == 148);
}

// --- the oracle itself: the fixture's 148 opaque named colors, read
// from the REAL specification text at test time, matched name-for-name
// and channel-for-channel against BOTH named_colors.cpp's own table
// (lookup_named_color()) AND the real parsing pipeline (parse_color()) -
// "lookup_named_color/parse_color batem canal a canal" (the order of
// service this file closes).

GLINTFX_TEST(named_color_table_matches_the_css_color_4_specification) {
    const std::string fixture_text = read_fixture();
    const std::vector<fixture_color_row> fixture_rows = parse_fixture_rows(fixture_text);
    GLINTFX_CHECK(fixture_rows.size() == 148);

    // Bijection, nome<->fixture: named_color_count() is 149 (148 opaque
    // + "transparent" - named_colors.hpp's own header comment), so the
    // CODE side of this compare is every entry EXCEPT "transparent"
    // (checked on its own, below, against the SS6.3 literal - it is
    // not part of the SS6.1 table this fixture extracts from at all).
    const std::size_t code_count = named_color_count();
    GLINTFX_CHECK(code_count == 149);
    GLINTFX_CHECK(fixture_rows.size() == code_count - 1);

    std::vector<std::string> code_names_excluding_transparent;
    code_names_excluding_transparent.reserve(code_count - 1);
    for (std::size_t i = 0; i < code_count; ++i) {
        const named_color_entry &entry = named_color_at(i);
        if (entry.name != "transparent") {
            code_names_excluding_transparent.emplace_back(entry.name);
        }
    }
    std::ranges::sort(code_names_excluding_transparent);
    const std::vector<std::string> fixture_names = sorted_names(fixture_rows);

    std::println("named_color_table_matches_the_css_color_4_specification: {} fixture name(s), "
                 "{} code name(s) (excluding \"transparent\")",
                 fixture_names.size(), code_names_excluding_transparent.size());
    GLINTFX_CHECK(fixture_names == code_names_excluding_transparent);

    // Channel-for-channel, both consumption paths - a mismatch here
    // means the TABLE itself carries a wrong value the bijection check
    // above cannot see (it only proves the NAME sets match).
    std::vector<std::string> mismatches;
    int checked = 0;
    for (const fixture_color_row &fixture_row : fixture_rows) {
        glintfx::gltfx_rgba8 looked_up{};
        const bool found = lookup_named_color(fixture_row.name, looked_up);
        if (!found) {
            mismatches.push_back(
                std::format("\"{}\": lookup_named_color() nao encontrou o nome", fixture_row.name));
            continue;
        }
        if (!channels_equal(looked_up, fixture_row.value)) {
            mismatches.push_back(std::format(
                "\"{}\": doc diz {} {} {}, lookup_named_color() tem {} {} {}", fixture_row.name,
                fixture_row.value.red, fixture_row.value.green, fixture_row.value.blue,
                looked_up.red, looked_up.green, looked_up.blue));
        }

        const color_parse_result parsed = parse_color(fixture_row.name);
        if (!parsed.ok) {
            mismatches.push_back(std::format(
                "\"{}\": parse_color() recusou o proprio nome da tabela", fixture_row.name));
            continue;
        }
        const glintfx::gltfx_rgba8 back = glintfx::gltfx_rgba_to_srgb8(parsed.value);
        if (!channels_equal(back, fixture_row.value)) {
            mismatches.push_back(std::format(
                "\"{}\": doc diz {} {} {}, parse_color() (round-trip sRGB8) tem {} {} {}",
                fixture_row.name, fixture_row.value.red, fixture_row.value.green,
                fixture_row.value.blue, back.red, back.green, back.blue));
        }
        ++checked;
    }

    for (const std::string &mismatch : mismatches) {
        std::println(stderr, "named_color_table_matches_the_css_color_4_specification: {}",
                     mismatch);
    }
    std::println("named_color_table_matches_the_css_color_4_specification: {} row(s) checked, {} "
                 "mismatch(es)",
                 checked, mismatches.size());
    GLINTFX_CHECK(checked == 148);
    GLINTFX_CHECK(mismatches.empty());
}

// --- "transparent" (CSS Color 4 SS6.3): NOT part of the SS6.1 table
// this fixture extracts from (named_colors.hpp/.cpp's own header
// comments), so it is pinned here against the literal SS6.3 itself
// defines ("The 'transparent' keyword ... specifies a transparent
// black") - external spec fact, the SAME "not derivable from our own
// fixture, marked as such" shape gfss_declaration_registry_doc_oracle_
// test.cpp's own spec_derived table already uses for six refused-
// shorthand details (GODS_LAWS.md L-27).

GLINTFX_TEST(transparent_keyword_matches_the_css_color_4_specification_ss6_3_literal) {
    const std::string fixture_text = read_fixture();
    const std::vector<fixture_color_row> fixture_rows = parse_fixture_rows(fixture_text);

    // "transparent" must NEVER be one of the 148 fixture rows - it is
    // not part of the opaque named-colors table at all (this file's
    // own top comment, and tests/tools/extract_css_named_colors.py's
    // own fixture_header()).
    const bool present_in_fixture = std::ranges::any_of(
        fixture_rows, [](const fixture_color_row &row) { return row.name == "transparent"; });
    GLINTFX_CHECK(!present_in_fixture);

    constexpr glintfx::gltfx_rgba8 k_transparent_black{.red = 0, .green = 0, .blue = 0, .alpha = 0};

    glintfx::gltfx_rgba8 looked_up{};
    GLINTFX_CHECK(lookup_named_color("transparent", looked_up));
    GLINTFX_CHECK(channels_equal(looked_up, k_transparent_black));

    const color_parse_result parsed = parse_color("transparent");
    GLINTFX_CHECK(parsed.ok);
    const glintfx::gltfx_rgba8 back = glintfx::gltfx_rgba_to_srgb8(parsed.value);
    GLINTFX_CHECK(channels_equal(back, k_transparent_black));

    std::println("transparent_keyword_matches_the_css_color_4_specification_ss6_3_literal: "
                 "lookup_named_color()={} {} {} {}, parse_color() round-trip={} {} {} {}",
                 looked_up.red, looked_up.green, looked_up.blue, looked_up.alpha, back.red,
                 back.green, back.blue, back.alpha);
}
