#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# EN: PROVENANCE (DEC-PROBE-CORPUS, W27, TODO.md) -- this file is a VERBATIM copy (body
#     byte-identical below this header, verified `md5sum` against the source BEFORE this
#     header was added -- `8a65739b27bf55606cfaa26da876e351`, both sides -- copied via
#     plain `cp`, never pasted/retyped, precisely to avoid the "a byte gets lost in
#     silence" risk a manual transcription of a byte-exact corpus generator would carry)
#     of gusworld's own deterministic corpus generator, offered to glintfx 2026-07-30 as
#     a fixture for the regression tests of the A-1 (`DEC-NOTHROW`) and A-2
#     (`DEC-FORMAT-SURFACE`) findings.
#       Source repo : gusworld_ia_autocomm (the git bus between glintfx and its GusWorld
#                      consumer -- private repo, not this one).
#       Source path : assets/probe-decode/gen_corpus.py
#       Source SHA  : 882cae0766fb3cdf5c43410b86148aa1f87557cf (HEAD of that path at the
#                      time of this copy; full history for the file at that commit:
#                      882cae0 "fix(probe-decode): o 31 do glintfx esta certo, o meu 34
#                      era o ls entrando num dir", dc96e07 "fix(probe-decode): o gerador
#                      agora PRODUZ o arquivo que o README manda usar", 82fc994
#                      "assets(probe-decode): entrega a sonda ao glintfx, com o gerador
#                      consertado").
#     Only THIS header (everything from the `SPDX-License-Identifier` line above down to
#     the closing `# ---` marker below) was added on the glintfx side. Not one line of
#     the generator's own logic was touched -- the value of this fixture (per
#     DEC-PROBE-CORPUS's own argument: "the test of the fix must use the SAME input that
#     caught the bug") depends on it staying byte-identical to what the consumer ran, so
#     glintfx treats it as adopted, not owned: future updates from the bus should land as
#     a fresh `cp` + a new SHA line here, never a hand-edit of the body.
#     Sibling companion `probe_mem.cpp` (same bus commit, same directory) was NOT
#     adopted verbatim -- its ~50-line VmHWM/`typeid`-on-caught-exception METHOD is cited
#     as a design reference in this repo's own `image_decode_probe_corpus_sanity.cpp`
#     (which reuses the two-stage fork()+`setrlimit(RLIMIT_AS)` calibrate-then-squeeze
#     oracle this repo's `image_decode_hardening_sanity.cpp` already proved, applied to
#     THIS generator's own `png_pal_12000.png`), not copied byte-for-byte the way this
#     generator was -- see that test file's own top comment for the full rationale.
#     GENERATION, NOT COMMITTING: `glintfx/tests/CMakeLists.txt` runs this script ONCE,
#     at build time (a CMake custom command, output under the build tree), to produce
#     the fixtures `image_decode_probe_corpus_sanity.cpp` reads. The generated bytes
#     themselves are NEVER committed to this repository -- only this generator is.
# PT: PROVENIÊNCIA (DEC-PROBE-CORPUS, W27, TODO.md) -- este arquivo é uma cópia VERBATIM
#     (corpo byte-idêntico abaixo deste cabeçalho, verificado por `md5sum` contra a fonte
#     ANTES deste cabeçalho ser somado -- `8a65739b27bf55606cfaa26da876e351` dos dois
#     lados -- copiado via `cp` puro, nunca colado/retranscrito, precisamente para evitar
#     o risco de "um byte se perde em silêncio" que uma transcrição manual de um gerador
#     de corpus byte-exato carregaria) do próprio gerador de corpus determinístico do
#     gusworld, oferecido ao glintfx em 2026-07-30 como fixture para os testes de
#     regressão dos achados A-1 (`DEC-NOTHROW`) e A-2 (`DEC-FORMAT-SURFACE`).
#       Repo fonte  : gusworld_ia_autocomm (o bus git entre glintfx e o consumidor
#                      GusWorld -- repo privado, não este).
#       Caminho     : assets/probe-decode/gen_corpus.py
#       SHA fonte   : 882cae0766fb3cdf5c43410b86148aa1f87557cf (HEAD daquele caminho no
#                      momento desta cópia; histórico completo do arquivo naquele commit:
#                      882cae0 "fix(probe-decode): o 31 do glintfx esta certo, o meu 34
#                      era o ls entrando num dir", dc96e07 "fix(probe-decode): o gerador
#                      agora PRODUZ o arquivo que o README manda usar", 82fc994
#                      "assets(probe-decode): entrega a sonda ao glintfx, com o gerador
#                      consertado").
#     Só ESTE cabeçalho (tudo da linha `SPDX-License-Identifier` acima até o marcador
#     `# ---` de fechamento abaixo) foi somado do lado do glintfx. Nenhuma linha da
#     própria lógica do gerador foi tocada -- o valor desta fixture (pelo próprio
#     argumento do DEC-PROBE-CORPUS: "o teste do conserto tem de usar a MESMA entrada que
#     pegou o bug") depende de continuar byte-idêntica ao que o consumidor rodou, então o
#     glintfx trata isto como ADOTADO, não possuído: atualizações futuras vindas do bus
#     devem chegar como um `cp` novo + uma linha de SHA nova aqui, nunca uma edição à mão
#     do corpo.
#     O companheiro irmão `probe_mem.cpp` (mesmo commit do bus, mesmo diretório) NÃO foi
#     adotado verbatim -- o MÉTODO dele de ~50 linhas (VmHWM/`typeid` sobre exceção
#     capturada) é citado como referência de desenho no próprio
#     `image_decode_probe_corpus_sanity.cpp` deste repo (que reusa o oráculo de dois
#     estágios fork()+`setrlimit(RLIMIT_AS)` calibrar-depois-apertar que o próprio
#     `image_decode_hardening_sanity.cpp` deste repo já provou, aplicado ao próprio
#     `png_pal_12000.png` DESTE gerador), não copiado byte-a-byte como este gerador foi --
#     ver o próprio comentário de topo daquele arquivo de teste pro racional completo.
#     GERAR, NÃO COMMITAR: `glintfx/tests/CMakeLists.txt` roda este script UMA vez, em
#     build-time (um custom command do CMake, saída sob a árvore de build), para produzir
#     as fixtures que `image_decode_probe_corpus_sanity.cpp` lê. Os bytes gerados em si
#     NUNCA são commitados neste repositório -- só este gerador é.
# ---------------------------------------------------------------------------------------
"""Corpus enumerado para o review adversarial da fatia S1 (stbi_load -> glintfx::decode_image_file).

Enumera o espaco INTEIRO de:
  (a) modos de falha de I/O / arquivo hostil
  (b) tipos de PNG (color type x bit depth) que o req_comp=4 do stbi_load normalizava
  (c) formatos NAO-PNG (o STBI_ONLY_PNG antigo rejeitava; o glintfx compila PNG+JPEG+TGA)
  (d) dimensoes de borda
"""
import os
import random
import shutil
import struct
import zlib
from pathlib import Path

# Saida: argv[1] > env CORPUS_OUT > ./corpus ao lado deste script.
# Nada de caminho absoluto embutido: este arquivo e compartilhado entre projetos.
import sys
_default = Path(__file__).resolve().parent / "corpus"
OUT = Path(sys.argv[1] if len(sys.argv) > 1 else os.environ.get("CORPUS_OUT", _default))
if OUT.exists():
    shutil.rmtree(OUT)
OUT.mkdir(parents=True)

from PIL import Image


def png_chunk(tag: bytes, data: bytes) -> bytes:
    return (struct.pack(">I", len(data)) + tag + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))


def raw_png(path: Path, w: int, h: int, color_type: int, bit_depth: int, rows: bytes,
            palette: bytes = b"", trns: bytes = b"") -> None:
    """Monta um PNG a mao (permite color types que o PIL nao expoe direto)."""
    ihdr = struct.pack(">IIBBBBB", w, h, bit_depth, color_type, 0, 0, 0)
    body = b"\x89PNG\r\n\x1a\n" + png_chunk(b"IHDR", ihdr)
    if palette:
        body += png_chunk(b"PLTE", palette)
    if trns:
        body += png_chunk(b"tRNS", trns)
    body += png_chunk(b"IDAT", zlib.compress(rows, 9))
    body += png_chunk(b"IEND", b"")
    path.write_bytes(body)


def scanlines(h: int, per_row: bytes) -> bytes:
    return b"".join(b"\x00" + per_row for _ in range(h))


made = []


def note(name: str, desc: str):
    made.append((name, desc))


# ---------------------------------------------------------------- (b) tipos de PNG
# color type 0 = grayscale, 2 = RGB, 3 = paletizado, 4 = gray+alpha, 6 = RGBA
raw_png(OUT / "png_gray8.png", 4, 4, 0, 8, scanlines(4, bytes([0, 64, 128, 255])))
note("png_gray8.png", "PNG grayscale 8-bit (color type 0), 4x4")

raw_png(OUT / "png_gray_alpha8.png", 4, 4, 4, 8,
        scanlines(4, bytes([10, 255, 20, 128, 30, 1, 40, 0])))
note("png_gray_alpha8.png", "PNG gray+alpha 8-bit (color type 4), 4x4")

raw_png(OUT / "png_rgb8.png", 4, 4, 2, 8,
        scanlines(4, bytes([255, 0, 0, 0, 255, 0, 0, 0, 255, 7, 8, 9])))
note("png_rgb8.png", "PNG RGB 8-bit SEM alpha (color type 2), 4x4")

pal = bytes([255, 0, 0, 0, 255, 0, 0, 0, 255, 9, 9, 9])
raw_png(OUT / "png_palette8.png", 4, 4, 3, 8, scanlines(4, bytes([0, 1, 2, 3])), palette=pal)
note("png_palette8.png", "PNG paletizado 8-bit (color type 3, PLTE), 4x4")

raw_png(OUT / "png_palette8_trns.png", 4, 4, 3, 8, scanlines(4, bytes([0, 1, 2, 3])),
        palette=pal, trns=bytes([255, 128, 0, 64]))
note("png_palette8_trns.png", "PNG paletizado + tRNS (alpha por indice), 4x4")

# ---------------------------------------------------------------------------
# PALETIZADO GRANDE: o unico caso do corpus capaz de ESGOTAR memoria, e o que
# dispara o A-1 (bad_alloc escapando do decode) sob `ulimit -v`.
#
# Por que PALETIZADO e nao RGBA8: aqui o buffer intermediario do stb tem 1
# byte por pixel (indice) e a saida tem 4 (RGBA), logo a copia extra do
# decode_image_file soma sobre o pico. Em RGBA8 o pico interno do proprio stb
# ja e 2x a saida e os dois caminhos EMPATAM -- um RGBA8 grande nao dispara o
# bug, e essa e a unica razao pela qual ele sobreviveu a duas provas de
# equivalencia byte-a-byte.
#
# 12000x12000 = 144 Mpx: 144 MB de indices, 576 MB de RGBA. Comprime para
# ~140 KB porque as linhas sao identicas (zlib mata a redundancia), entao o
# arquivo e pequeno e a EXPANSAO e enorme -- exatamente o que se quer para
# testar exaustao sem carregar fixture pesada.
_PAL_BIG = 12000
_pal_row = bytes([0] * (_PAL_BIG // 4) + [1] * (_PAL_BIG // 4)
                 + [2] * (_PAL_BIG // 4) + [3] * (_PAL_BIG - 3 * (_PAL_BIG // 4)))
raw_png(OUT / "png_pal_12000.png", _PAL_BIG, _PAL_BIG, 3, 8,
        scanlines(_PAL_BIG, _pal_row), palette=pal)
note("png_pal_12000.png",
     f"PNG paletizado {_PAL_BIG}x{_PAL_BIG} (144 Mpx, 576 MB decodificado) - DISPARA o A-1")

raw_png(OUT / "png_gray1.png", 8, 4, 0, 1, scanlines(4, bytes([0b10110010])))
note("png_gray1.png", "PNG grayscale 1 bit-per-pixel (sub-byte), 8x4")

raw_png(OUT / "png_gray4.png", 4, 4, 0, 4, scanlines(4, bytes([0x0F, 0xA5])))
note("png_gray4.png", "PNG grayscale 4 bits-per-pixel (sub-byte), 4x4")

raw_png(OUT / "png_rgb16.png", 2, 2, 2, 16,
        scanlines(2, struct.pack(">6H", 0xFFFF, 0x0000, 0x8000, 0x1234, 0x00FF, 0xFF00)))
note("png_rgb16.png", "PNG RGB 16 bits POR CANAL (color type 2, depth 16), 2x2")

raw_png(OUT / "png_rgba16.png", 2, 2, 6, 16,
        scanlines(2, struct.pack(">8H", 0xFFFF, 0, 0, 0x8080, 0, 0xFFFF, 0, 0xFFFF)))
note("png_rgba16.png", "PNG RGBA 16 bits POR CANAL (color type 6, depth 16), 2x2")

# RGBA 8 normal (controle) + alpha parcial
img = Image.new("RGBA", (4, 4))
img.putdata([(i * 16, 255 - i * 16, 128, (i * 17) % 256) for i in range(16)])
img.save(OUT / "png_rgba8.png")
note("png_rgba8.png", "PNG RGBA8 normal com alpha parcial (CONTROLE), 4x4")

img = Image.new("RGBA", (4, 4), (0, 0, 0, 0))
img.save(OUT / "png_rgba8_fully_transparent.png")
note("png_rgba8_fully_transparent.png", "PNG RGBA8 100% transparente (bbox found=false), 4x4")

Image.new("RGBA", (1, 1), (255, 128, 64, 200)).save(OUT / "png_1x1.png")
note("png_1x1.png", "PNG RGBA8 1x1")

Image.new("RGBA", (4096, 1), (10, 20, 30, 40)).save(OUT / "png_4096x1.png")
note("png_4096x1.png", "PNG RGBA8 4096x1 (muito largo, 1px de altura)")

Image.new("RGBA", (1, 4096), (10, 20, 30, 40)).save(OUT / "png_1x4096.png")
note("png_1x4096.png", "PNG RGBA8 1x4096 (muito alto, 1px de largura)")

# interlaced (Adam7)
Image.new("RGBA", (16, 16), (1, 2, 3, 4)).save(OUT / "png_interlaced.png", interlace=1)
note("png_interlaced.png", "PNG RGBA8 interlaced Adam7, 16x16")

# ---------------------------------------------------------------- (a) I/O e corrupcao
good = (OUT / "png_rgba8.png").read_bytes()

(OUT / "empty.png").write_bytes(b"")
note("empty.png", "arquivo de 0 byte")

(OUT / "text.png").write_bytes(b"isto nao e uma imagem, e texto puro\n" * 4)
note("text.png", "texto renomeado para .png")

(OUT / "truncated_half.png").write_bytes(good[: len(good) // 2])
note("truncated_half.png", "PNG real cortado exatamente na metade")

(OUT / "truncated_header_only.png").write_bytes(good[:33])
note("truncated_header_only.png", "PNG real: so assinatura + IHDR (sem IDAT)")

bad_crc = bytearray(good)
bad_crc[-5] ^= 0xFF  # corrompe o CRC do IEND
(OUT / "bad_crc_iend.png").write_bytes(bytes(bad_crc))
note("bad_crc_iend.png", "PNG com CRC do IEND corrompido")

bad_idat = bytearray(good)
# acha o IDAT e corrompe 1 byte do payload comprimido (quebra o zlib, IHDR fica valido)
i = bytes(bad_idat).find(b"IDAT")
bad_idat[i + 8] ^= 0xFF
(OUT / "bad_idat_payload.png").write_bytes(bytes(bad_idat))
note("bad_idat_payload.png", "PNG com payload do IDAT corrompido (header valido, zlib quebrado)")

huge_dim = bytearray(good)
struct.pack_into(">II", huge_dim, 16, 0x7FFFFFF0, 0x7FFFFFF0)  # w/h absurdos no IHDR
huge_dim[29:33] = struct.pack(">I", zlib.crc32(bytes(huge_dim[12:29])) & 0xFFFFFFFF)
(OUT / "png_huge_dims.png").write_bytes(bytes(huge_dim))
note("png_huge_dims.png", "PNG com w=h=0x7FFFFFF0 no IHDR (overflow de dimensao)")

zero_dim = bytearray(good)
struct.pack_into(">II", zero_dim, 16, 0, 0)
zero_dim[29:33] = struct.pack(">I", zlib.crc32(bytes(zero_dim[12:29])) & 0xFFFFFFFF)
(OUT / "png_zero_dims.png").write_bytes(bytes(zero_dim))
note("png_zero_dims.png", "PNG com w=h=0 no IHDR")

(OUT / "noperm.png").write_bytes(good)
os.chmod(OUT / "noperm.png", 0o000)
note("noperm.png", "PNG valido SEM permissao de leitura (chmod 000)")

(OUT / "adir.png").mkdir()
note("adir.png", "DIRETORIO com nome .png")

os.symlink(OUT / "nao_existe_alvo.png", OUT / "dangling_symlink.png")
note("dangling_symlink.png", "symlink quebrado")

note("__MISSING__/nao_existe.png", "arquivo inexistente (caminho invalido)")
note("__NULLPTR__", "path == nullptr")

# ---------------------------------------------------------------- (c) formatos NAO-PNG
Image.new("RGB", (8, 8), (200, 100, 50)).save(OUT / "jpeg_as_png.png", format="JPEG")
note("jpeg_as_png.png", "JPEG real com extensao .png")

Image.new("RGBA", (8, 8), (1, 2, 3, 4)).save(OUT / "tga_as_png.png", format="TGA")
note("tga_as_png.png", "TGA real com extensao .png")

Image.new("RGB", (8, 8), (9, 9, 9)).save(OUT / "bmp_as_png.png", format="BMP")
note("bmp_as_png.png", "BMP real com extensao .png (nem PNG nem JPEG nem TGA)")

Image.new("P", (8, 8)).save(OUT / "gif_as_png.png", format="GIF")
note("gif_as_png.png", "GIF real com extensao .png")

# TGA falso: lixo que passa no sniff FROUXO do stbi__tga_test.
# Header TGA (18 bytes): id_len, colormap_type, image_type, ...
#   image_type 2 = RGB nao comprimido; bits_per_pixel 32.
tga_hdr = bytes([0, 0, 2]) + b"\x00" * 5 + struct.pack("<HHHHBB", 0, 0, 4096, 4096, 32, 0)
# SEMENTE FIXA 20260730: o valor deste corpus e ser byte-exato entre maquinas.
# os.urandom() NAO e reproduzivel -- era o defeito da versao anterior deste script.
_rng = random.Random(20260730)
_noise64 = bytes(_rng.randrange(256) for _ in range(64))
(OUT / "fake_tga_garbage.png").write_bytes(tga_hdr + _noise64)
note("fake_tga_garbage.png",
     "LIXO de 82 bytes com header TGA plausivel (w=h=4096, 32bpp) - o sniff frouxo do TGA")

tga_hdr_huge = bytes([0, 0, 2]) + b"\x00" * 5 + struct.pack("<HHHHBB", 0, 0, 65535, 65535, 32, 0)
_noise16 = bytes(_rng.randrange(256) for _ in range(16))
(OUT / "fake_tga_huge.png").write_bytes(tga_hdr_huge + _noise16)
note("fake_tga_huge.png",
     "LIXO de 34 bytes com header TGA declarando 65535x65535 32bpp (~16 GiB de pixel)")

print(f"{len(made)} casos em {OUT}")
for name, desc in made:
    print(f"  {name:34s} {desc}")
