#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# prepare_arch_ports_fixture.sh - ARCH-PORTS, TDD case R4 (GODS_LAWS.md
# L-09/L-20): stages the REAL production sources connect_smoke.cpp
# needs into tests/container/_arch_ports_src/, so the Containerfile
# (whose own build CONTEXT is tests/container/, not the repository
# root - .github/workflows/ci.yml's "Constroi a imagem" step) can COPY
# them without widening the docker build context to the whole repo,
# which would risk vacuuming up another agent's own concurrent, large,
# in-progress build/ directories at the repository root (measured
# present and 9-83MB each while this fatia was being built).
#
# STAGES A COPY, NEVER THE SOURCE OF TRUTH: nothing under
# tests/container/_arch_ports_src/ is ever committed
# (.gitignore) or hand-edited - it is regenerated by this script every
# time, directly from the real tree, so there is no risk of the
# container's build silently drifting from the adapter this fatia's
# own unit/failure tests already exercise.
#
# WHOLE-TREE SCAN, NOT A HAND-MAINTAINED LIST OF DIRECTORIES
# (GODS_LAWS.md L-17/L-40, 06/09/2026 - segundo conserto do CTO): this
# function used to `cp` each file by its own full hand-typed path (one
# line per file), and after that broke a THIRD time in two days it was
# rewritten to scan EIGHT hand-named directories instead - progress,
# but still a list a future file could fall outside of: a header added
# under include/glintfx/platform/gl/ that same day (D-W6b-25, GL-
# CONTEXT) needed a NINTH line added to the list, by hand, in the same
# commit, or the fixture would have gone back to failing the exact same
# way. copy_source_tree() below replaces the eight named directories
# with THREE recursive roots - src/, include/ and tests/parity/ - that
# this project's own real build already treats as the whole of its
# source and public-header trees (cmake/GlintfxLibrary.cmake's own
# target_sources() glob-free list still names every file it compiles
# explicitly; staging is not compiling, and copying an extra file that
# no Containerfile `g++` invocation happens to name costs nothing - see
# that function's own header comment). A file added ANYWHERE under one
# of these three roots - a new platform backend, a new public header, a
# second fixture under tests/parity/ - is staged automatically, from
# now on, with no second edit to this script ever required again.
#
# THE GEMEO THIS FIX ALSO HAD TO OWN UP TO (GODS_LAWS.md L-17): staging
# more than a Containerfile invocation actually compiles is exactly the
# blind spot check_container_fixture_inventory.py already closed for
# the OTHER half of this same wiring (a fixture binary entering the
# image without entering the parity inventory) - a full-tree stage
# could, in principle, silently paper over a Containerfile `g++` line
# that names a header the fixture no longer needs, or hide a genuinely
# absent header behind one from an unrelated directory that happens to
# share a name. tests/tools/check_container_fixture_includes.py (run at
# the end of main(), below) is the gate that closes THAT blind spot: it
# reads the Containerfile's own `g++`/`gcc` invocations, walks the real
# `#include` closure of every TU they name, and reproves the one
# failure mode a whole-tree stage cannot rule out by construction - a
# header that resolves nowhere in the fixture but exists in the real
# tree, under a root this script did not stage (GODS_LAWS.md L-36:
# producer and verifier are DISTINCT pieces of code on purpose, so this
# script's own bug in deciding what to stage is not the same bug as the
# portao's in deciding whether staging worked).
#
# glintfx/export.hpp is the ONE file here that is NOT copied from the
# real tree: normally CMake's generate_export_header() (cmake/
# GlintfxLibrary.cmake) writes it, expanding GLINTFX_API to
# __declspec/visibility attributes for the REAL shared-library build.
# This fixture never builds glintfx_library at all - connect_smoke.cpp
# links display_adapter.cpp/err.cpp/err_code.cpp directly into ONE
# static executable, with no .so boundary to cross - so GLINTFX_API
# only needs to expand to NOTHING here, the same shape
# GLINTFX_STATIC_DEFINE gives it in this project's own static build
# mode (cmake/GlintfxLibrary.cmake's own comment on
# glintfx_apply_static_define()).
#
# Usage: prepare_arch_ports_fixture.sh <repo-root>
#
# Each function below does one thing (GODS_LAWS.md L-17).

set -eu

fail() {
    echo "prepare_arch_ports_fixture.sh: $1" >&2
    exit 1
}

require_repo_root_arg() {
    [ "$#" -eq 1 ] || fail "usage: prepare_arch_ports_fixture.sh <repo-root>"
    [ -d "$1" ] || fail "directory not found: $1"
}

stage_dir() {
    repo_root="$1"
    printf '%s\n' "$repo_root/tests/container/_arch_ports_src"
}

reset_stage() {
    target="$1"
    rm -rf "$target"
}

# Stages every .hpp/.cpp/.h file found ANYWHERE under repo_root/$rel_root
# (recursive, unlike the old directory-by-directory copy_source_dir()
# this replaces), preserving the relative path under $target/$rel_root.
#
# NO PROCESS PER FILE (GODS_LAWS.md L-11): one `find` and a two-sided
# `tar` pipe move the whole subtree in a fixed, small number of
# processes, never one per file staged - the same shape this project's
# own build already avoids by never spawning a compiler invocation per
# translation unit outside of Ninja's own job pool. `find -printf '%P'`
# (GNU extension; this script only ever runs on the ubuntu-latest
# runner .github/workflows/ci.yml's own `wayland-container` job uses,
# and on a developer's own Linux machine, both GNU findutils) prints
# each match already RELATIVE to the search root, so the first `tar -C
# "$src_dir"` archives relative paths and the second `tar -C "$dst_dir"`
# reconstructs the identical relative layout underneath it, with no
# string surgery on the paths in between.
#
# GODS_LAWS.md L-40 non-empty-scan floor, on BOTH ends of the copy: a
# root that comes back with ZERO files to stage is refused before any
# copy happens (a typo'd rel_root, or a root genuinely emptied by a
# future refactor, must never look like "nothing to copy" the same way
# every other gate in this project refuses that shape); and the number
# of files actually found under $dst_dir afterwards must equal the
# number found under $src_dir before - the batch-copy analogue of
# GODS_LAWS.md L-36's "a tool that processes many items in one call can
# crash partway through and hide the loss": a `tar` pipe that dies
# midway is exactly that tool, so this function counts both ends and
# never trusts the copy's own exit status alone.
copy_source_tree() {
    repo_root="$1"
    target="$2"
    rel_root="$3"

    src_dir="$repo_root/$rel_root"
    dst_dir="$target/$rel_root"
    [ -d "$src_dir" ] || fail "raiz nao encontrada: $rel_root ($src_dir)"
    mkdir -p "$dst_dir"

    found=$(find "$src_dir" -type f \( -name '*.hpp' -o -name '*.cpp' -o -name '*.h' \) | wc -l | tr -d ' ')
    [ "$found" -gt 0 ] ||
        fail "varredura vazia em $rel_root (GODS_LAWS.md L-40) - a raiz existe mas nao tem nenhum .hpp/.cpp/.h para estagiar"

    find "$src_dir" -type f \( -name '*.hpp' -o -name '*.cpp' -o -name '*.h' \) -printf '%P\0' |
        tar --null -C "$src_dir" -T - -cf - |
        tar -xf - -C "$dst_dir"

    copied=$(find "$dst_dir" -type f | wc -l | tr -d ' ')
    [ "$copied" -eq "$found" ] ||
        fail "$rel_root: $found encontrado(s) mas $copied copiado(s) (GODS_LAWS.md L-36/L-40) - a copia em lote nao terminou igual ao que foi varrido"

    echo "prepare_arch_ports_fixture.sh: $rel_root - $found encontrado(s) / $copied copiado(s)"
}

# The THREE roots this whole image's Containerfile ever needs a source
# or public header from, today: every production .cpp/.hpp under src/,
# every public header under include/, and the fixture source itself
# under tests/parity/ (outside this script's own tests/container/
# directory - the Containerfile's own build CONTEXT - which is why it
# needs staging too, same as every production source does). A fourth
# root reaching outside these three, in the future, is its own new
# copy_source_tree() call added in the same commit that first needs it
# - exactly as true of this list as it was of the eight-directory list
# it replaces, just never again one narrower than "the whole tree".
copy_real_sources() {
    repo_root="$1"
    target="$2"

    total_found=0
    total_copied=0

    copy_source_tree "$repo_root" "$target" "src"
    total_found=$((total_found + found))
    total_copied=$((total_copied + copied))

    copy_source_tree "$repo_root" "$target" "include"
    total_found=$((total_found + found))
    total_copied=$((total_copied + copied))

    copy_source_tree "$repo_root" "$target" "tests/parity"
    total_found=$((total_found + found))
    total_copied=$((total_copied + copied))

    echo "prepare_arch_ports_fixture.sh: total - $total_found encontrado(s) / $total_copied copiado(s)"
}

write_export_header_stub() {
    target="$1"
    mkdir -p "$target/include/glintfx"
    cat > "$target/include/glintfx/export.hpp" <<'EOF'
// SPDX-License-Identifier: AGPL-3.0-or-later
// export.hpp - STUB, generated by prepare_arch_ports_fixture.sh, NOT
// the real cmake/GlintfxLibrary.cmake output. See that script's own
// header comment for why an empty GLINTFX_API is correct HERE
// specifically (a single statically-linked executable, no .so
// boundary).
#pragma once
#define GLINTFX_API
EOF
}

# Last step of main(), after the stage is complete: resolves every
# `#include` the Containerfile's own `g++`/`gcc` invocations can reach
# against what was ACTUALLY staged, never against what this script
# only INTENDS to stage (GODS_LAWS.md L-36 - a producer never grades
# its own homework). See tests/tools/check_container_fixture_includes.py's
# own header comment for the full shape of what this closes.
verify_fixture_includes() {
    repo_root="$1"
    target="$2"

    python3 "$repo_root/tests/tools/check_container_fixture_includes.py" --compare \
        "$repo_root/tests/container/Containerfile" \
        "$repo_root/tests/container" \
        "$target" \
        "$repo_root" ||
        fail "portao de includes da fixture reprovou (ver acima)"
}

# Sibling of verify_fixture_includes() above, closing the blind spot
# THAT gate cannot by construction: it proves every #include resolves,
# never that the resulting TUs actually LINK. A production atom that
# starts calling into a sibling .cpp file through a header both TUs
# already #include (no new #include appears anywhere) is invisible to
# verify_fixture_includes() and visible only to a real `ld` - which is
# exactly what happened on 08/09/2026 (flush_retry_policy.cpp, server
# run 34192811273, see tests/tools/check_container_fixture_link.py's
# own header comment for the full account and TODO.md's INBOX,
# 07/09/2026, for the family this closes: three prior mordidas of
# "lista de fontes mantida a mao", this being the fourth). Runs the
# Containerfile's own g++/gcc invocations for real, against the tree
# THIS run of main() just staged, BEFORE `docker build` ever starts
# (GODS_LAWS.md L-40: a link gap reproves here, not eleven minutes into
# the far more expensive image build).
verify_fixture_link() {
    repo_root="$1"
    target="$2"

    # `set -eu` is on (see top of file) - a bare command followed by a
    # SEPARATE `rc=$?` line would trip errexit on any non-zero exit
    # (77 included) and kill the whole script before this function's
    # own rc==77 handling ever ran (measured: bash -x showed execution
    # stop dead right after the python3 line, never reaching `rc=$?`).
    # `|| rc=$?` keeps the failing command inside a construct errexit
    # exempts, same idiom `fail()` callers elsewhere in this file rely
    # on (a bare command immediately followed by `||`).
    rc=0
    python3 "$repo_root/tests/tools/check_container_fixture_link.py" --exec \
        "$repo_root/tests/container/Containerfile" \
        "$repo_root/tests/container" \
        "$target" \
        "$repo_root" || rc=$?

    # rc 77: GATE_SKIP_RETURN_CODE em check_container_fixture_link.py -
    # o portao PULOU de forma declarada (mensagem propria ja impressa
    # acima) porque este HOST nao tem os pacotes wayland de
    # desenvolvimento que --exec precisaria pra rodar o g++/wayland-
    # scanner do Containerfile FORA do container (GODS_LAWS.md L-17/
    # L-36, conserto 08/09/2026, server run 34215308251: gemeo exato do
    # conserto do compilador em --selftest, achado pelo team-lead no
    # mesmo log). NAO e reprovacao: o `docker build` que main() ainda
    # vai rodar logo em seguida continua sendo a prova real do link,
    # DENTRO do container, que ja tem esses pacotes.
    if [ "$rc" -eq 77 ]; then
        echo "prepare_arch_ports_fixture.sh: portao de link da fixture PULADO neste host (ver mensagem acima) - docker build abaixo continua sendo a prova real" >&2
        return 0
    fi
    [ "$rc" -eq 0 ] || fail "portao de link da fixture reprovou (ver acima)"
}

main() {
    require_repo_root_arg "$@"
    repo_root="$1"
    target="$(stage_dir "$repo_root")"

    reset_stage "$target"
    copy_real_sources "$repo_root" "$target"
    write_export_header_stub "$target"

    echo "prepare_arch_ports_fixture.sh: staged $(find "$target" -type f | wc -l | tr -d ' ') file(s) under $target"

    verify_fixture_includes "$repo_root" "$target"
    verify_fixture_link "$repo_root" "$target"
}

main "$@"
