#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# prepare_arch_ports_fixture.sh - ARCH-PORTS, TDD case R4 (GODS_LAWS.md
# L-09/L-20): stages the REAL production sources connect_smoke.cpp
# needs into tests/container/_arch_ports_src/, so the Containerfile
# (whose own build CONTEXT is tests/container/, not the repository
# root - .github/workflows/ci.yml's "Constroi a imagem" step) can COPY
# them without widening the docker build context to the whole repo,
# which would risk vacuuming up another agent's own concurrent, large,
# in-progress build/ directories at the repository root (measured
# present and 9-83MB each while this fatia was being built).
#
# STAGES A COPY, NEVER THE SOURCE OF TRUTH: nothing under
# tests/container/_arch_ports_src/ is ever committed
# (.gitignore) or hand-edited - it is regenerated by this script every
# time, from src/platform/wayland/, src/core/ and include/glintfx/core/
# directly, so there is no risk of the container's build silently
# drifting from the adapter this fatia's own unit/failure tests
# already exercise.
#
# glintfx/export.hpp is the ONE file here that is NOT copied from the
# real tree: normally CMake's generate_export_header() (cmake/
# GlintfxLibrary.cmake) writes it, expanding GLINTFX_API to
# __declspec/visibility attributes for the REAL shared-library build.
# This fixture never builds glintfx_library at all - connect_smoke.cpp
# links display_adapter.cpp/err.cpp/err_code.cpp directly into ONE
# static executable, with no .so boundary to cross - so GLINTFX_API
# only needs to expand to NOTHING here, the same shape
# GLINTFX_STATIC_DEFINE gives it in this project's own static build
# mode (cmake/GlintfxLibrary.cmake's own comment on
# glintfx_apply_static_define()).
#
# Usage: prepare_arch_ports_fixture.sh <repo-root>
#
# Each function below does one thing (GODS_LAWS.md L-17).

set -eu

fail() {
    echo "prepare_arch_ports_fixture.sh: $1" >&2
    exit 1
}

require_repo_root_arg() {
    [ "$#" -eq 1 ] || fail "usage: prepare_arch_ports_fixture.sh <repo-root>"
    [ -d "$1" ] || fail "directory not found: $1"
}

stage_dir() {
    repo_root="$1"
    printf '%s\n' "$repo_root/tests/container/_arch_ports_src"
}

reset_stage() {
    target="$1"
    rm -rf "$target"
    mkdir -p "$target/src/platform/wayland" "$target/src/platform/window" \
        "$target/src/platform/input" "$target/src/platform/port" "$target/src/core" \
        "$target/include/glintfx/core" "$target/include/glintfx/platform/window" \
        "$target/tests/parity"
}

copy_real_sources() {
    repo_root="$1"
    target="$2"

    cp "$repo_root/src/platform/wayland/display_adapter.hpp" \
        "$target/src/platform/wayland/display_adapter.hpp"
    cp "$repo_root/src/platform/wayland/display_adapter.cpp" \
        "$target/src/platform/wayland/display_adapter.cpp"

    # WL-DISPLAY fatia B: display_adapter.cpp now calls into
    # global_catalog's own member functions from its registry
    # listener - registry_smoke.cpp's own build (Containerfile) needs
    # both staged here for the same reason connect_smoke.cpp's build
    # already needs display_adapter.cpp itself.
    cp "$repo_root/src/platform/wayland/global_catalog.hpp" \
        "$target/src/platform/wayland/global_catalog.hpp"
    cp "$repo_root/src/platform/wayland/global_catalog.cpp" \
        "$target/src/platform/wayland/global_catalog.cpp"

    # WL-WINDOW fatia W-B (docs/plano-w6a-janela.md fatia 5):
    # shell_smoke.cpp's own build (Containerfile) needs both staged
    # here for the same reason connect_smoke.cpp's build already needs
    # display_adapter.cpp itself - shell_adapter.cpp calls into
    # wayland_display_adapter and global_catalog directly, and
    # shell_requirements.cpp is the pure half it calls before ever
    # binding.
    cp "$repo_root/src/platform/wayland/shell_requirements.hpp" \
        "$target/src/platform/wayland/shell_requirements.hpp"
    cp "$repo_root/src/platform/wayland/shell_requirements.cpp" \
        "$target/src/platform/wayland/shell_requirements.cpp"
    cp "$repo_root/src/platform/wayland/shell_adapter.hpp" \
        "$target/src/platform/wayland/shell_adapter.hpp"
    cp "$repo_root/src/platform/wayland/shell_adapter.cpp" \
        "$target/src/platform/wayland/shell_adapter.cpp"

    # WL-WINDOW fatia W-E (docs/plano-w6a-janela.md fatia 8):
    # window_smoke.cpp's own build (Containerfile) needs window_
    # adapter.cpp itself, window_configure_sequence.cpp (the pure xdg_
    # surface/xdg_toplevel configure-sequence translator it calls into),
    # and the three OS-agnostic src/platform/window/ files (window_
    # state.cpp, window_desc_validation.cpp, utf8_validation.cpp)
    # window_adapter.cpp's own apply_desc()/xdg_surface_configure()
    # call - same "stage the real production sources" reasoning as
    # every other entry in this function.
    cp "$repo_root/src/platform/wayland/window_configure_sequence.hpp" \
        "$target/src/platform/wayland/window_configure_sequence.hpp"
    cp "$repo_root/src/platform/wayland/window_configure_sequence.cpp" \
        "$target/src/platform/wayland/window_configure_sequence.cpp"
    cp "$repo_root/src/platform/wayland/window_adapter.hpp" \
        "$target/src/platform/wayland/window_adapter.hpp"
    cp "$repo_root/src/platform/wayland/window_adapter.cpp" \
        "$target/src/platform/wayland/window_adapter.cpp"
    cp "$repo_root/src/platform/window/window_state.hpp" \
        "$target/src/platform/window/window_state.hpp"
    cp "$repo_root/src/platform/window/window_state.cpp" \
        "$target/src/platform/window/window_state.cpp"
    cp "$repo_root/src/platform/window/window_desc_validation.hpp" \
        "$target/src/platform/window/window_desc_validation.hpp"
    cp "$repo_root/src/platform/window/window_desc_validation.cpp" \
        "$target/src/platform/window/window_desc_validation.cpp"
    cp "$repo_root/src/platform/window/utf8_validation.hpp" \
        "$target/src/platform/window/utf8_validation.hpp"
    cp "$repo_root/src/platform/window/utf8_validation.cpp" \
        "$target/src/platform/window/utf8_validation.cpp"

    # WL-SEAT fatia S-B (docs/plano-w6a-janela.md fatia 12): seat_
    # test.cpp's own build (Containerfile) needs seat_adapter.cpp
    # itself (it calls into wayland_display_adapter directly, same
    # reasoning as shell_adapter.cpp above) and the OS-agnostic
    # seat_capabilities.{hpp,cpp} (platform/input/) that wl_seat_
    # capabilities() writes into.
    cp "$repo_root/src/platform/input/seat_capabilities.hpp" \
        "$target/src/platform/input/seat_capabilities.hpp"
    cp "$repo_root/src/platform/input/seat_capabilities.cpp" \
        "$target/src/platform/input/seat_capabilities.cpp"
    cp "$repo_root/src/platform/wayland/seat_adapter.hpp" \
        "$target/src/platform/wayland/seat_adapter.hpp"
    cp "$repo_root/src/platform/wayland/seat_adapter.cpp" \
        "$target/src/platform/wayland/seat_adapter.cpp"

    cp "$repo_root/src/core/err.cpp" "$target/src/core/err.cpp"
    cp "$repo_root/src/core/err_code.cpp" "$target/src/core/err_code.cpp"

    cp "$repo_root/include/glintfx/core/err.hpp" "$target/include/glintfx/core/err.hpp"
    cp "$repo_root/include/glintfx/core/err_code.hpp" "$target/include/glintfx/core/err_code.hpp"

    # WL-WINDOW-HANDLE (docs/plano-w6a-janela.md fatias 6/9/11, absorbed
    # into one fatia): window_parity_test.cpp's own build (Containerfile)
    # is the FIRST fixture in this whole image that touches the PUBLIC
    # API (glintfx::gltfx_display/gltfx_window) instead of an internal
    # adapter directly - it needs the two public headers, the port
    # concepts/display_connection template they build on, BOTH facade
    # .cpp files (display_facade.cpp/window_facade.cpp - the two
    # translation units that actually define display_impl/window_impl),
    # the internal display_impl.hpp they share, and selected_display_
    # adapter.hpp/selected_window_adapter.hpp (the compile-time
    # selection display_facade.cpp/window_facade.cpp each include under
    # their own #if defined(_WIN32) branch - never reached on this
    # Linux-only image, but still parsed).
    cp "$repo_root/include/glintfx/platform/window/display.hpp" \
        "$target/include/glintfx/platform/window/display.hpp"
    cp "$repo_root/include/glintfx/platform/window/window.hpp" \
        "$target/include/glintfx/platform/window/window.hpp"
    cp "$repo_root/src/platform/port/display_connection_port.hpp" \
        "$target/src/platform/port/display_connection_port.hpp"
    cp "$repo_root/src/platform/port/display_connection.hpp" \
        "$target/src/platform/port/display_connection.hpp"
    cp "$repo_root/src/platform/port/display_backend_port.hpp" \
        "$target/src/platform/port/display_backend_port.hpp"
    cp "$repo_root/src/platform/port/window_adapter_port.hpp" \
        "$target/src/platform/port/window_adapter_port.hpp"
    cp "$repo_root/src/platform/window/display_impl.hpp" \
        "$target/src/platform/window/display_impl.hpp"
    cp "$repo_root/src/platform/window/display_facade.cpp" \
        "$target/src/platform/window/display_facade.cpp"
    cp "$repo_root/src/platform/window/window_facade.cpp" \
        "$target/src/platform/window/window_facade.cpp"
    cp "$repo_root/src/platform/wayland/selected_display_adapter.hpp" \
        "$target/src/platform/wayland/selected_display_adapter.hpp"
    cp "$repo_root/src/platform/wayland/selected_window_adapter.hpp" \
        "$target/src/platform/wayland/selected_window_adapter.hpp"

    # The fixture source itself lives under tests/parity/, outside this
    # script's own tests/container/ directory (the Containerfile's own
    # build CONTEXT) - staged here for the SAME reason every production
    # source above is: a file the Containerfile's `COPY` needs to reach
    # has to already be somewhere under that context by the time
    # `docker build` runs.
    cp "$repo_root/tests/parity/window_parity_test.cpp" \
        "$target/tests/parity/window_parity_test.cpp"
}

write_export_header_stub() {
    target="$1"
    cat > "$target/include/glintfx/export.hpp" <<'EOF'
// SPDX-License-Identifier: AGPL-3.0-or-later
// export.hpp - STUB, generated by prepare_arch_ports_fixture.sh, NOT
// the real cmake/GlintfxLibrary.cmake output. See that script's own
// header comment for why an empty GLINTFX_API is correct HERE
// specifically (a single statically-linked executable, no .so
// boundary).
#pragma once
#define GLINTFX_API
EOF
}

main() {
    require_repo_root_arg "$@"
    repo_root="$1"
    target="$(stage_dir "$repo_root")"

    reset_stage "$target"
    copy_real_sources "$repo_root" "$target"
    write_export_header_stub "$target"

    echo "prepare_arch_ports_fixture.sh: staged $(find "$target" -type f | wc -l | tr -d ' ') file(s) under $target"
}

main "$@"
