#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# prepare_arch_ports_fixture.sh - ARCH-PORTS, TDD case R4 (GODS_LAWS.md
# L-09/L-20): stages the REAL production sources connect_smoke.cpp
# needs into tests/container/_arch_ports_src/, so the Containerfile
# (whose own build CONTEXT is tests/container/, not the repository
# root - .github/workflows/ci.yml's "Constroi a imagem" step) can COPY
# them without widening the docker build context to the whole repo,
# which would risk vacuuming up another agent's own concurrent, large,
# in-progress build/ directories at the repository root (measured
# present and 9-83MB each while this fatia was being built).
#
# STAGES A COPY, NEVER THE SOURCE OF TRUTH: nothing under
# tests/container/_arch_ports_src/ is ever committed
# (.gitignore) or hand-edited - it is regenerated by this script every
# time, from src/platform/wayland/, src/core/ and include/glintfx/core/
# directly, so there is no risk of the container's build silently
# drifting from the adapter this fatia's own unit/failure tests
# already exercise.
#
# glintfx/export.hpp is the ONE file here that is NOT copied from the
# real tree: normally CMake's generate_export_header() (cmake/
# GlintfxLibrary.cmake) writes it, expanding GLINTFX_API to
# __declspec/visibility attributes for the REAL shared-library build.
# This fixture never builds glintfx_library at all - connect_smoke.cpp
# links display_adapter.cpp/err.cpp/err_code.cpp directly into ONE
# static executable, with no .so boundary to cross - so GLINTFX_API
# only needs to expand to NOTHING here, the same shape
# GLINTFX_STATIC_DEFINE gives it in this project's own static build
# mode (cmake/GlintfxLibrary.cmake's own comment on
# glintfx_apply_static_define()).
#
# Usage: prepare_arch_ports_fixture.sh <repo-root>
#
# Each function below does one thing (GODS_LAWS.md L-17).

set -eu

fail() {
    echo "prepare_arch_ports_fixture.sh: $1" >&2
    exit 1
}

require_repo_root_arg() {
    [ "$#" -eq 1 ] || fail "usage: prepare_arch_ports_fixture.sh <repo-root>"
    [ -d "$1" ] || fail "directory not found: $1"
}

stage_dir() {
    repo_root="$1"
    printf '%s\n' "$repo_root/tests/container/_arch_ports_src"
}

reset_stage() {
    target="$1"
    rm -rf "$target"
    mkdir -p "$target/src/platform/wayland" "$target/src/core" \
        "$target/include/glintfx/core"
}

copy_real_sources() {
    repo_root="$1"
    target="$2"

    cp "$repo_root/src/platform/wayland/display_adapter.hpp" \
        "$target/src/platform/wayland/display_adapter.hpp"
    cp "$repo_root/src/platform/wayland/display_adapter.cpp" \
        "$target/src/platform/wayland/display_adapter.cpp"

    cp "$repo_root/src/core/err.cpp" "$target/src/core/err.cpp"
    cp "$repo_root/src/core/err_code.cpp" "$target/src/core/err_code.cpp"

    cp "$repo_root/include/glintfx/core/err.hpp" "$target/include/glintfx/core/err.hpp"
    cp "$repo_root/include/glintfx/core/err_code.hpp" "$target/include/glintfx/core/err_code.hpp"
}

write_export_header_stub() {
    target="$1"
    cat > "$target/include/glintfx/export.hpp" <<'EOF'
// SPDX-License-Identifier: AGPL-3.0-or-later
// export.hpp - STUB, generated by prepare_arch_ports_fixture.sh, NOT
// the real cmake/GlintfxLibrary.cmake output. See that script's own
// header comment for why an empty GLINTFX_API is correct HERE
// specifically (a single statically-linked executable, no .so
// boundary).
#pragma once
#define GLINTFX_API
EOF
}

main() {
    require_repo_root_arg "$@"
    repo_root="$1"
    target="$(stage_dir "$repo_root")"

    reset_stage "$target"
    copy_real_sources "$repo_root" "$target"
    write_export_header_stub "$target"

    echo "prepare_arch_ports_fixture.sh: staged $(find "$target" -type f | wc -l | tr -d ' ') file(s) under $target"
}

main "$@"
