#pragma once

#include <cstdint>
#include <string_view>

#include <glintfx/export.hpp>

// core/version.hpp - runtime version of the glintfx library (FUND-1,
// relocated to the core layer in FUND-2 by GODS_LAWS.md L-19).
//
// Kept apart from <glintfx/version_macros.hpp> (header generated by
// CMake with the GLINTFX_VERSION_* defines): this header is the public,
// committed API; the generated one is a build detail that changes with
// every version. It lives in glintfx/core/ because it is a pure
// type/value; it does not touch the OS.
//
// ABI contract (GODS_LAWS.md L-22): no exception crosses this public
// API. Both functions below are noexcept and return by value; no
// function in this header, nor any path it can reach in the library,
// throws across the public boundary.

namespace glintfx {

struct version {
    std::uint32_t major;
    std::uint32_t minor;
    std::uint32_t patch;
};

[[nodiscard]] GLINTFX_API version runtime_version() noexcept;
[[nodiscard]] GLINTFX_API std::string_view version_string() noexcept;

}  // namespace glintfx
