// SPDX-License-Identifier: AGPL-3.0-or-later
#pragma once

#include <cstdint>
#include <string_view>

#include <glintfx/export.hpp>

// core/version.hpp - runtime version of the glintfx library (FUND-1,
// relocated to the core layer in FUND-2 by GODS_LAWS.md L-19).
//
// Kept apart from <glintfx/version_macros.hpp> (header generated by
// CMake with the GLINTFX_VERSION_* defines): this header is the public,
// committed API; the generated one is a build detail that changes with
// every version. It lives in glintfx/core/ because it is a pure
// type/value; it does not touch the OS.
//
// ABI contract (GODS_LAWS.md L-22): no exception crosses this public
// API. Both functions below are noexcept and return by value; no
// function in this header, nor any path it can reach in the library,
// throws across the public boundary.
//
// Field names (FIX-CONSUMO, achado A8): NOT `major`/`minor`. On Linux,
// the system header "sysmacros dot h" (historically dragged in by the
// system header that declares basic POSIX types) defines
// `major`/`minor`/`makedev` as function-like macros; any external
// consumer whose translation unit includes that system header before
// this one has `v.major`/`v.minor` mangled by the preprocessor into a
// call expression, with a compiler error that points nowhere near this
// file. `major_version`/`minor_version`/`patch_version` do not collide
// with any known system macro, and are renamed together (not just the
// two colliding fields) so the struct stays internally consistent.
//
// (This comment spells out the header names in prose, not as literal
// #include directives, on purpose: tests/tools/check_layers.sh greps
// this file for OS-header include patterns, and an angle-bracket
// mention here would trip a layer-violation false positive on a
// comment that merely explains a naming rationale.)

namespace glintfx {

// Four fields, not three (GODS_LAWS.md L-26, VER-4C): the tag is
// vA.B.C.D, and tweak_version is D, the packaging-only component with
// no code change. It is the fourth and LAST field, appended rather
// than inserted, so this one-time layout reopening (allowed only
// pre-1.0, SOVERSION 0, zero known external consumer) does not also
// reorder the three fields an existing reader already depends on.
struct version {
    std::uint32_t major_version;
    std::uint32_t minor_version;
    std::uint32_t patch_version;
    std::uint32_t tweak_version;
};

[[nodiscard]] GLINTFX_API version runtime_version() noexcept;
[[nodiscard]] GLINTFX_API std::string_view version_string() noexcept;

} // namespace glintfx
